import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const VERSION="v26.0",GRAPH=`https://graph.facebook.com/${VERSION}`;
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...CORS,"Content-Type":"application/json"}});
const cleanAct=(v:string)=>String(v||"").trim().replace(/^act_/i,"");
function fill(pattern:string,campaign:string,site:any){return String(pattern||"").replaceAll("{{campaign}}",campaign||"Campaign").replaceAll("{{area}}",site?.area||"").replaceAll("{{slug}}",site?.slug||"").replace(/\s*\|\s*\|\s*/g," | ").replace(/^\s*\|\s*|\s*\|\s*$/g,"").trim()}
async function graphGet(path:string,token:string,params:Record<string,string>={}){const u=new URL(`${GRAPH}/${path.replace(/^\//,"")}`);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v));u.searchParams.set("access_token",token);const r=await fetch(u),d=await r.json();if(!r.ok||d.error)throw new Error(d?.error?.message||`Meta API ${r.status}`);return d}
async function graphPost(path:string,token:string,params:Record<string,string>={}){const b=new URLSearchParams();Object.entries(params).forEach(([k,v])=>b.set(k,v));b.set("access_token",token);const r=await fetch(`${GRAPH}/${path.replace(/^\//,"")}`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:b}),d=await r.json();if(!r.ok||d.error)throw new Error(`${d?.error?.message||`Meta API ${r.status}`}${d?.error?.error_user_msg?` — ${d.error.error_user_msg}`:""}`);return d}
async function audiences(account:string,token:string){let next=`${GRAPH}/act_${account}/customaudiences?fields=id,name&limit=200&access_token=${encodeURIComponent(token)}`,out:any[]=[],guard=0;while(next&&guard++<30){const r=await fetch(next),d=await r.json();if(!r.ok||d.error)throw new Error(d?.error?.message||`Audience lookup ${r.status}`);out.push(...(d.data||[]));next=d.paging?.next||""}return out}
function landing(site:any,config:any,ex:any){const base=String(config.baseUrl||"").replace(/\/+$/,"");return ex?.landing_url||(site.domain?(/^https?:\/\//i.test(site.domain)?site.domain:`https://${site.domain}`):`${base}/${site.slug}`)}
Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:CORS}); if(req.method!=="POST")return json({error:"Method not allowed"},405);
 try{
  const auth=req.headers.get("Authorization")||"",url=Deno.env.get("SUPABASE_URL")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,user=createClient(url,anon,{global:{headers:{Authorization:auth}}}),db=createClient(url,service),body=await req.json(),rolloutId=String(body.rollout_id||""),action=String(body.action||"");
  if(!rolloutId)return json({error:"rollout_id required"},400);
  const {data:ctx,error}=await user.rpc("org_admin_central_campaign_rollout",{p_rollout:rolloutId});if(error||!ctx?.rollout)return json({error:"Not authorised"},403);const rollout=ctx.rollout,orgId=String(rollout.organisation_id||""),sites=ctx.sites||[];const {data:isGlobal}=await user.rpc("is_org_global_admin",{p_org:orgId});if(!isGlobal)return json({error:"Global admin required"},403);
  const [{data:conn},{data:cfg},{data:exceptions}]=await Promise.all([db.from("central_campaign_meta_connections").select("*").eq("rollout_id",rolloutId).maybeSingle(),db.from("central_campaign_ad_settings").select("config").eq("rollout_id",rolloutId).eq("platform","facebook").maybeSingle(),user.rpc("org_admin_meta_exceptions",{p_rollout:rolloutId})]);
  if(!conn)return json({error:"Connect Meta first"},400);const token=String(conn.access_token||""),account=cleanAct(conn.ad_account_id),config={...(cfg?.config||{}),...(body.config||{})},exMap=new Map((exceptions||[]).map((x:any)=>[String(x.site_id),x])),included=sites.filter((s:any)=>!exMap.get(String(s.id))?.excluded);
  if(action==="preflight"){
   const all=await audiences(account,token),byName=new Map(all.map((a:any)=>[String(a.name||"").trim(),String(a.id||"")]));const missing:string[]=[];for(const s of included){const n=fill(String(config.audiencePattern||"{{area}}AUDIENCE.CSV"),rollout.title,s);if(!byName.get(n))missing.push(n)}
   const live=included.filter((s:any)=>s.status==="live").length,valid=included.filter((s:any)=>{try{const u=new URL(landing(s,config,exMap.get(String(s.id))||{}));return /^https?:$/.test(u.protocol)}catch{return false}}).length,copy=!!String(config.body||"").trim()&&!!String(config.headline||"").trim(),political=config.politicalCampaign===false||String(config.special||"")==="ISSUES_ELECTIONS_POLITICS",budget=included.reduce((a:number,s:any)=>a+Number(exMap.get(String(s.id))?.budget||config.budget||0),0),variants=config.variantBEnabled?2:1;
   const checks={microsites_live:{ok:live===included.length,ready:live,total:included.length},landing_urls:{ok:valid===included.length,ready:valid,total:included.length},audiences:{ok:missing.length===0,ready:included.length-missing.length,total:included.length,missing},copy:{ok:copy},page:{ok:!!conn.page_id},ad_account:{ok:!!account},budget:{ok:budget>0,total_daily:budget},special_category:{ok:political}};return json({ok:Object.values(checks).every((x:any)=>x.ok),checks,expected:included.length,variants,total_ads:included.length*variants,missing});
  }
  if(action==="create_drafts"){
   const all=await audiences(account,token),byName=new Map(all.map((a:any)=>[String(a.name||"").trim(),String(a.id||"")])),planned=included.map((s:any)=>{const ex=exMap.get(String(s.id))||{},n=fill(String(config.audiencePattern||"{{area}}AUDIENCE.CSV"),rollout.title,s);return{site:s,ex,audience_name:n,audience_id:byName.get(n)||"",budget:Number(ex.budget||config.budget||10),landing:landing(s,config,ex)}}),missing=planned.filter((x:any)=>!x.audience_id);if(missing.length&&!body.allow_missing_audiences)return json({error:`${missing.length} Meta audience${missing.length===1?"":"s"} not found`,missing:missing.map((x:any)=>x.audience_name)},400);
   const {data:existing}=await db.from("central_campaign_meta_batches").select("id,campaign_id,status").eq("rollout_id",rolloutId).in("status",["creating","created","partial"]).order("created_at",{ascending:false}).limit(1).maybeSingle();if(existing&&!body.force)return json({error:"A Meta draft batch already exists",existing},409);
   const campaignName=fill(String(config.campaignPattern||"{{campaign}}"),rollout.title,planned[0]?.site||{}),special=String(config.special||"").trim(),params:any={name:campaignName,objective:String(config.objective||"OUTCOME_TRAFFIC"),status:"PAUSED",buying_type:"AUCTION",special_ad_categories:JSON.stringify(special?[special]:[]),is_adset_budget_sharing_enabled:"false"};if(special)params.special_ad_category_country=JSON.stringify([String(config.country||"GB")]);const camp=await graphPost(`act_${account}/campaigns`,token,params),campaignId=String(camp.id||"");if(!campaignId)throw new Error("Meta did not return campaign ID");const batchId=crypto.randomUUID();await db.from("central_campaign_meta_batches").insert({id:batchId,organisation_id:orgId,rollout_id:rolloutId,campaign_id:campaignId,campaign_name:campaignName,status:"creating",expected_objects:planned.length,graph_version:VERSION,metadata:{variants:config.variantBEnabled?2:1}});
   let created=0;const results:any[]=[];for(const x of planned){const s=x.site,name=fill(String(config.adSetPattern||"{{campaign}} | {{area}}"),rollout.title,s),targeting:any={geo_locations:{countries:[String(config.country||"GB")]}};if(x.audience_id)targeting.custom_audiences=[{id:x.audience_id}];let adsetId="",err="";try{const a=await graphPost(`act_${account}/adsets`,token,{name,campaign_id:campaignId,daily_budget:String(Math.max(100,Math.round(x.budget*100))),billing_event:"IMPRESSIONS",optimization_goal:String(config.optimizationGoal||"LANDING_PAGE_VIEWS"),bid_strategy:"LOWEST_COST_WITHOUT_CAP",targeting:JSON.stringify(targeting),status:"PAUSED"});adsetId=String(a.id||"");created++}catch(e){err=e instanceof Error?e.message:String(e)}await db.from("central_campaign_meta_drafts").insert({batch_id:batchId,organisation_id:orgId,rollout_id:rolloutId,site_id:s.id,area:s.area,audience_name:x.audience_name,audience_id:x.audience_id,adset_id:adsetId||null,adset_name:name,landing_url:x.landing,graphic_filename:fill(String(config.creativePattern||"{{slug}}.jpg"),rollout.title,s),status:adsetId?"created":"failed",error:err||null,metadata:{budget:x.budget,excluded:false}});results.push({area:s.area,adset_id:adsetId||null,status:adsetId?"created":"failed",error:err||null})}
   const status=created===planned.length?"created":created?"partial":"failed";await db.from("central_campaign_meta_batches").update({status,created_objects:created,error:status==="created"?null:`${planned.length-created} ad sets failed`,updated_at:new Date().toISOString()}).eq("id",batchId);return json({ok:status==="created",status,batch_id:batchId,campaign_id:campaignId,created,expected:planned.length,results});
  }
  if(action==="set_campaign_status"){const {data:b}=await db.from("central_campaign_meta_batches").select("campaign_id").eq("rollout_id",rolloutId).order("created_at",{ascending:false}).limit(1).maybeSingle();if(!b?.campaign_id)return json({error:"No Meta campaign found"},400);const status=String(body.status||"PAUSED").toUpperCase();await graphPost(String(b.campaign_id),token,{status});return json({ok:true,status})}
  if(action==="set_adset_status"){const siteId=String(body.site_id||""),{data:d}=await db.from("central_campaign_meta_drafts").select("adset_id").eq("rollout_id",rolloutId).eq("site_id",siteId).not("adset_id","is",null).order("created_at",{ascending:false}).limit(1).maybeSingle();if(!d?.adset_id)return json({error:"No ad set found"},400);const status=String(body.status||"PAUSED").toUpperCase();await graphPost(String(d.adset_id),token,{status});return json({ok:true,status})}
  if(action==="sync_statuses"){const {data:b}=await db.from("central_campaign_meta_batches").select("campaign_id").eq("rollout_id",rolloutId).order("created_at",{ascending:false}).limit(1).maybeSingle(),{data:ds}=await db.from("central_campaign_meta_drafts").select("id,adset_id").eq("rollout_id",rolloutId),{data:as}=await db.from("central_campaign_meta_assets").select("id,ad_id").eq("rollout_id",rolloutId);let campaign=null;if(b?.campaign_id)campaign=await graphGet(String(b.campaign_id),token,{fields:"id,name,status,effective_status"});const adsets=[];for(const d of ds||[]){if(!d.adset_id)continue;try{const x=await graphGet(String(d.adset_id),token,{fields:"id,name,status,effective_status"});adsets.push(x);await db.from("central_campaign_meta_drafts").update({metadata:{meta_status:x.status,effective_status:x.effective_status},updated_at:new Date().toISOString()}).eq("id",d.id)}catch{}}const ads=[];for(const a of as||[]){if(!a.ad_id)continue;try{const x=await graphGet(String(a.ad_id),token,{fields:"id,name,status,effective_status"});ads.push(x);await db.from("central_campaign_meta_assets").update({metadata:{meta_status:x.status,effective_status:x.effective_status},updated_at:new Date().toISOString()}).eq("id",a.id)}catch{}}return json({ok:true,campaign,adsets,ads})}
  if(action==="retry_failed_adsets"){const {data:b}=await db.from("central_campaign_meta_batches").select("campaign_id").eq("rollout_id",rolloutId).order("created_at",{ascending:false}).limit(1).maybeSingle(),{data:failed}=await db.from("central_campaign_meta_drafts").select("*").eq("rollout_id",rolloutId).eq("status","failed");if(!b?.campaign_id)return json({error:"No Meta campaign found"},400);let retried=0;for(const d of failed||[]){const s=sites.find((x:any)=>String(x.id)===String(d.site_id)),ex=exMap.get(String(d.site_id))||{};if(!s||ex.excluded)continue;const targeting:any={geo_locations:{countries:[String(config.country||"GB")]}};if(d.audience_id)targeting.custom_audiences=[{id:d.audience_id}];try{const a=await graphPost(`act_${account}/adsets`,token,{name:d.adset_name,campaign_id:String(b.campaign_id),daily_budget:String(Math.max(100,Math.round(Number(ex.budget||config.budget||10)*100))),billing_event:"IMPRESSIONS",optimization_goal:String(config.optimizationGoal||"LANDING_PAGE_VIEWS"),bid_strategy:"LOWEST_COST_WITHOUT_CAP",targeting:JSON.stringify(targeting),status:"PAUSED"});await db.from("central_campaign_meta_drafts").update({adset_id:String(a.id||""),status:"created",error:null,updated_at:new Date().toISOString()}).eq("id",d.id);retried++}catch(e){await db.from("central_campaign_meta_drafts").update({error:e instanceof Error?e.message:String(e),updated_at:new Date().toISOString()}).eq("id",d.id)}}return json({ok:true,retried,failed:(failed||[]).length-retried})}
  return json({error:"Unknown action"},400);
 }catch(e){return json({error:e instanceof Error?e.message:String(e)},500)}
});
