-- Stage 17: consolidated Organisation Admin navigation and advertising overview.
-- Applied to Campaign Platform Supabase on 2026-09-03.
create or replace function public.org_admin_advertising_overview(p_org uuid)
returns table(rollout_id uuid,title text,rollout_status text,sites_count bigint,live_sites bigint,meta_connected boolean,ad_account_name text,meta_campaign_id text,meta_campaign_status text,adsets_count bigint,ads_count bigint,failed_adsets bigint,spend numeric,impressions bigint,clicks bigint,landing_page_views bigint,supporters bigint,cost_per_supporter numeric)
language sql stable security definer set search_path=public as $$
with latest_batch as (select distinct on (rollout_id) rollout_id,campaign_id,status from public.central_campaign_meta_batches order by rollout_id,created_at desc),site_counts as (select rollout_id,count(*)::bigint sites_count,count(*) filter(where status='live')::bigint live_sites from public.central_campaign_sites group by rollout_id),draft_counts as (select rollout_id,count(*) filter(where adset_id is not null)::bigint adsets_count,count(*) filter(where status='failed')::bigint failed_adsets from public.central_campaign_meta_drafts group by rollout_id),asset_counts as (select rollout_id,count(*) filter(where ad_id is not null)::bigint ads_count from public.central_campaign_meta_assets group by rollout_id),perf as (select rollout_id,coalesce(sum(spend),0)::numeric spend,coalesce(sum(impressions),0)::bigint impressions,coalesce(sum(clicks),0)::bigint clicks,coalesce(sum(landing_page_views),0)::bigint landing_page_views from public.central_campaign_meta_performance group by rollout_id),supp as (select rollout_id,count(*)::bigint supporters from public.central_campaign_supporters group by rollout_id)
select r.id,r.title,r.status,coalesce(sc.sites_count,0),coalesce(sc.live_sites,0),(mc.rollout_id is not null),mc.ad_account_name,lb.campaign_id,lb.status,coalesce(dc.adsets_count,0),coalesce(ac.ads_count,0),coalesce(dc.failed_adsets,0),coalesce(p.spend,0),coalesce(p.impressions,0),coalesce(p.clicks,0),coalesce(p.landing_page_views,0),coalesce(s.supporters,0),case when coalesce(s.supporters,0)>0 then round(coalesce(p.spend,0)/s.supporters::numeric,2) else 0 end from public.central_campaign_rollouts r left join site_counts sc on sc.rollout_id=r.id left join public.central_campaign_meta_connections mc on mc.rollout_id=r.id left join latest_batch lb on lb.rollout_id=r.id left join draft_counts dc on dc.rollout_id=r.id left join asset_counts ac on ac.rollout_id=r.id left join perf p on p.rollout_id=r.id left join supp s on s.rollout_id=r.id where r.organisation_id=p_org and public.is_org_admin(p_org) order by r.updated_at desc;
$$;
grant execute on function public.org_admin_advertising_overview(uuid) to authenticated;
revoke execute on function public.org_admin_advertising_overview(uuid) from anon;
