-- Stage 16: Meta campaign operations suite.
create table if not exists public.central_campaign_meta_exceptions (
  id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade,
  rollout_id uuid not null references public.central_campaign_rollouts(id) on delete cascade,
  site_id uuid not null references public.central_campaign_sites(id) on delete cascade,
  excluded boolean not null default false, budget numeric, landing_url text, copy_a text, headline_a text, copy_b text, headline_b text,
  creative_a text, creative_b text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(rollout_id,site_id)
);
alter table public.central_campaign_meta_exceptions enable row level security;
revoke all on public.central_campaign_meta_exceptions from anon,authenticated;
create or replace function public.org_admin_meta_exceptions(p_rollout uuid) returns setof public.central_campaign_meta_exceptions language sql stable security definer set search_path=public as $$ select e.* from public.central_campaign_meta_exceptions e join public.central_campaign_rollouts r on r.id=e.rollout_id where e.rollout_id=p_rollout and public.is_org_admin(r.organisation_id) order by e.created_at $$;
grant execute on function public.org_admin_meta_exceptions(uuid) to authenticated; revoke execute on function public.org_admin_meta_exceptions(uuid) from anon;
create or replace function public.org_admin_save_meta_exception(p_rollout uuid,p_site uuid,p_patch jsonb) returns boolean language plpgsql security definer set search_path=public as $$ declare v_org uuid; begin select organisation_id into v_org from public.central_campaign_rollouts where id=p_rollout; if v_org is null or not public.is_org_global_admin(v_org) then raise exception 'Not authorised'; end if; if not exists(select 1 from public.central_campaign_sites where id=p_site and rollout_id=p_rollout) then raise exception 'Site not in rollout'; end if; insert into public.central_campaign_meta_exceptions(organisation_id,rollout_id,site_id,excluded,budget,landing_url,copy_a,headline_a,copy_b,headline_b,creative_a,creative_b,metadata,updated_at) values(v_org,p_rollout,p_site,coalesce((p_patch->>'excluded')::boolean,false),nullif(p_patch->>'budget','')::numeric,nullif(p_patch->>'landing_url',''),nullif(p_patch->>'copy_a',''),nullif(p_patch->>'headline_a',''),nullif(p_patch->>'copy_b',''),nullif(p_patch->>'headline_b',''),nullif(p_patch->>'creative_a',''),nullif(p_patch->>'creative_b',''),coalesce(p_patch->'metadata','{}'::jsonb),now()) on conflict(rollout_id,site_id) do update set excluded=excluded.excluded,budget=excluded.budget,landing_url=excluded.landing_url,copy_a=excluded.copy_a,headline_a=excluded.headline_a,copy_b=excluded.copy_b,headline_b=excluded.headline_b,creative_a=excluded.creative_a,creative_b=excluded.creative_b,metadata=excluded.metadata,updated_at=now(); return true; end $$;
grant execute on function public.org_admin_save_meta_exception(uuid,uuid,jsonb) to authenticated; revoke execute on function public.org_admin_save_meta_exception(uuid,uuid,jsonb) from anon;
create or replace function public.org_admin_delete_meta_exception(p_rollout uuid,p_site uuid) returns boolean language plpgsql security definer set search_path=public as $$ declare v_org uuid; begin select organisation_id into v_org from public.central_campaign_rollouts where id=p_rollout; if v_org is null or not public.is_org_global_admin(v_org) then raise exception 'Not authorised'; end if; delete from public.central_campaign_meta_exceptions where rollout_id=p_rollout and site_id=p_site; return true; end $$;
grant execute on function public.org_admin_delete_meta_exception(uuid,uuid) to authenticated; revoke execute on function public.org_admin_delete_meta_exception(uuid,uuid) from anon;
create or replace function public.org_admin_meta_geography_results(p_rollout uuid) returns table(site_id uuid,area text,site_status text,spend numeric,impressions bigint,clicks bigint,landing_page_views bigint,supporters bigint,conversion_rate numeric,cost_per_supporter numeric) language sql stable security definer set search_path=public as $$ with r as (select organisation_id from public.central_campaign_rollouts where id=p_rollout), p as (select site_id,sum(spend)::numeric spend,sum(impressions)::bigint impressions,sum(clicks)::bigint clicks,sum(landing_page_views)::bigint lpv from public.central_campaign_meta_performance where rollout_id=p_rollout group by site_id), s as (select site_id,count(*)::bigint supporters from public.central_campaign_supporters where rollout_id=p_rollout group by site_id) select cs.id,cs.area,cs.status,coalesce(p.spend,0),coalesce(p.impressions,0),coalesce(p.clicks,0),coalesce(p.lpv,0),coalesce(s.supporters,0),case when coalesce(p.lpv,0)>0 then round((coalesce(s.supporters,0)::numeric/p.lpv::numeric)*100,2) else 0 end,case when coalesce(s.supporters,0)>0 then round(coalesce(p.spend,0)/s.supporters::numeric,2) else 0 end from public.central_campaign_sites cs left join p on p.site_id=cs.id left join s on s.site_id=cs.id where cs.rollout_id=p_rollout and public.is_org_admin((select organisation_id from r)) order by cs.area $$;
grant execute on function public.org_admin_meta_geography_results(uuid) to authenticated; revoke execute on function public.org_admin_meta_geography_results(uuid) from anon;
